reformat files according to linter settings

diff --git a/stow/shell/dot-functions b/stow/shell/dot-functions
--- a/stow/shell/dot-functions
+++ b/stow/shell/dot-functions
@@ -2,130 +2,130 @@
 
 # Create a new directory and enter it
 function mkd() {
-	mkdir -p "$@" && cd "$_" || return;
+	mkdir -p "$@" && cd "$_" || return
 }
 
 # Create a .tar.gz archive, using `zopfli`, `pigz` or `gzip` for compression
 function targz() {
-	local tmpFile="${*%/}.tar";
-	tar -cvf "${tmpFile}" --exclude=".DS_Store" "${@}" || return 1;
+	local tmpFile="${*%/}.tar"
+	tar -cvf "${tmpFile}" --exclude=".DS_Store" "${@}" || return 1
 
 	size=$(
-		stat -f"%z" "${tmpFile}" 2> /dev/null; # macOS `stat`
-		stat -c"%s" "${tmpFile}" 2> /dev/null;  # GNU `stat`
-	);
+		stat -f"%z" "${tmpFile}" 2>/dev/null # macOS `stat`
+		stat -c"%s" "${tmpFile}" 2>/dev/null # GNU `stat`
+	)
 
-	local cmd="";
-	if (( size < 52428800 )) && hash zopfli 2> /dev/null; then
+	local cmd=""
+	if ((size < 52428800)) && hash zopfli 2>/dev/null; then
 		# the .tar file is smaller than 50 MB and Zopfli is available; use it
-		cmd="zopfli";
+		cmd="zopfli"
 	else
-		if hash pigz 2> /dev/null; then
-			cmd="pigz";
+		if hash pigz 2>/dev/null; then
+			cmd="pigz"
 		else
-			cmd="gzip";
-		fi;
-	fi;
+			cmd="gzip"
+		fi
+	fi
 
-	echo "Compressing .tar ($((size / 1000)) kB) using \`${cmd}\`…";
-	"${cmd}" -v "${tmpFile}" || return 1;
-	[[ -f "${tmpFile}" ]] && rm "${tmpFile}";
+	echo "Compressing .tar ($((size / 1000)) kB) using \`${cmd}\`…"
+	"${cmd}" -v "${tmpFile}" || return 1
+	[[ -f "${tmpFile}" ]] && rm "${tmpFile}"
 
 	zippedSize=$(
-		stat -f"%z" "${tmpFile}.gz" 2> /dev/null; # macOS `stat`
-		stat -c"%s" "${tmpFile}.gz" 2> /dev/null; # GNU `stat`
-	);
+		stat -f"%z" "${tmpFile}.gz" 2>/dev/null # macOS `stat`
+		stat -c"%s" "${tmpFile}.gz" 2>/dev/null # GNU `stat`
+	)
 
-	echo "${tmpFile}.gz ($((zippedSize / 1000)) kB) created successfully.";
+	echo "${tmpFile}.gz ($((zippedSize / 1000)) kB) created successfully."
 }
 
 # Determine size of a file or total size of a directory
 function fs() {
-	if du -b /dev/null > /dev/null 2>&1; then
-		local arg=-sbh;
+	if du -b /dev/null >/dev/null 2>&1; then
+		local arg=-sbh
 	else
-		local arg=-sh;
+		local arg=-sh
 	fi
 	if [[ -n "$*" ]]; then
-		du $arg -- "$@";
+		du $arg -- "$@"
 	else
-		du $arg .[^.]* ./*;
-	fi;
+		du $arg .[^.]* ./*
+	fi
 }
 
 # Use Git’s colored diff when available
 if hash git &>/dev/null; then
 	function diff() {
-		git diff --no-index --color-words "$@";
+		git diff --no-index --color-words "$@"
 	}
-fi;
+fi
 
 # Create a data URL from a file
 function dataurl() {
-	local mimeType;
-	mimeType=$(file -b --mime-type "${1}");
+	local mimeType
+	mimeType=$(file -b --mime-type "${1}")
 	if [[ "${mimeType}" == text/* ]]; then
-		mimeType="${mimeType};charset=utf-8";
+		mimeType="${mimeType};charset=utf-8"
 	fi
-	echo "data:${mimeType};base64,$(openssl base64 -in "${1}" | tr -d '\n')";
+	echo "data:${mimeType};base64,$(openssl base64 -in "${1}" | tr -d '\n')"
 }
 
 # Start an HTTP server from the current directory, optionally specifying the port
 function server() {
-	local port="${1:-8000}";
+	local port="${1:-8000}"
 	sleep 1 && open "http://localhost:${port}/" &
-	python3 -m http.server "${port}";
+	python3 -m http.server "${port}"
 }
 
 # Compare original and gzipped file size
 function gz() {
-	local origsize, gzipsize, ratio;
-	origsize=$(wc -c < "${1}");
-	gzipsize=$(gzip -c "${1}" | wc -c);
-	ratio=$(echo "${gzipsize} * 100 / ${origsize}" | bc -l);
-	printf "orig: %d bytes\n" "${origsize}";
-	printf "gzip: %d bytes (%2.2f%%)\n" "${gzipsize}" "${ratio}";
+	local origsize, gzipsize, ratio
+	origsize=$(wc -c <"${1}")
+	gzipsize=$(gzip -c "${1}" | wc -c)
+	ratio=$(echo "${gzipsize} * 100 / ${origsize}" | bc -l)
+	printf "orig: %d bytes\n" "${origsize}"
+	printf "gzip: %d bytes (%2.2f%%)\n" "${gzipsize}" "${ratio}"
 }
 
 # Run `dig` and display the most useful info
 function digga() {
-	dig +nocmd "${1}" any +multiline +noall +answer;
+	dig +nocmd "${1}" any +multiline +noall +answer
 }
 
 # Show all the names (CNs and SANs) listed in the SSL certificate
 # for a given domain
 function getcertnames() {
 	if [[ -z "${1}" ]]; then
-		echo "ERROR: No domain specified.";
-		return 1;
-	fi;
+		echo "ERROR: No domain specified."
+		return 1
+	fi
 
-	local domain, tmp, certText;
+	local domain, tmp, certText
 
-	domain="${1}";
-	echo "Testing ${domain}…";
-	echo ""; # newline
+	domain="${1}"
+	echo "Testing ${domain}…"
+	echo "" # newline
 
-	tmp=$(echo -e "GET / HTTP/1.0\nEOT" \
-		| openssl s_client -connect "${domain}:443" -servername "${domain}" 2>&1);
+	tmp=$(echo -e "GET / HTTP/1.0\nEOT" |
+		openssl s_client -connect "${domain}:443" -servername "${domain}" 2>&1)
 
 	if [[ "${tmp}" = *"-----BEGIN CERTIFICATE-----"* ]]; then
-		certText=$(echo "${tmp}" \
-			| openssl x509 -text -certopt "no_aux, no_header, no_issuer, no_pubkey, \
-			no_serial, no_sigdump, no_signame, no_validity, no_version");
-		echo "Common Name:";
-		echo ""; # newline
-		echo "${certText}" | grep "Subject:" | sed -e "s/^.*CN=//" | sed -e "s/\/emailAddress=.*//";
-		echo ""; # newline
-		echo "Subject Alternative Name(s):";
-		echo ""; # newline
-		echo "${certText}" | grep -A 1 "Subject Alternative Name:" \
-			| sed -e "2s/DNS://g" -e "s/ //g" | tr "," "\n" | tail -n +2;
-		return 0;
+		certText=$(echo "${tmp}" |
+			openssl x509 -text -certopt "no_aux, no_header, no_issuer, no_pubkey, \
+			no_serial, no_sigdump, no_signame, no_validity, no_version")
+		echo "Common Name:"
+		echo "" # newline
+		echo "${certText}" | grep "Subject:" | sed -e "s/^.*CN=//" | sed -e "s/\/emailAddress=.*//"
+		echo "" # newline
+		echo "Subject Alternative Name(s):"
+		echo "" # newline
+		echo "${certText}" | grep -A 1 "Subject Alternative Name:" |
+			sed -e "2s/DNS://g" -e "s/ //g" | tr "," "\n" | tail -n +2
+		return 0
 	else
-		echo "ERROR: Certificate not found.";
-		return 1;
-	fi;
+		echo "ERROR: Certificate not found."
+		return 1
+	fi
 }
 
 # Normalize `open` across Linux, macOS, and Windows.
@@ -133,9 +133,9 @@ function getcertnames() {
 if [ ! "$(uname -s)" = 'Darwin' ]; then
 	if grep -q Microsoft /proc/version; then
 		# Ubuntu on Windows using the Linux subsystem
-		alias open='explorer.exe';
+		alias open='explorer.exe'
 	else
-		alias open='xdg-open';
+		alias open='xdg-open'
 	fi
 fi
 
@@ -143,10 +143,10 @@ fi
 # location
 function o() {
 	if [[ $# -eq 0 ]]; then
-		open .;
+		open .
 	else
-		open "$@";
-	fi;
+		open "$@"
+	fi
 }
 
 # `tre` is a shorthand for `tree` with hidden files and color enabled, ignoring
@@ -154,7 +154,7 @@ function o() {
 # `less` with options to preserve color and line numbers, unless the output is
 # small enough for one screen.
 function tre() {
-	tree -aC -I '.git|node_modules' --dirsfirst "$@" | less -FRNX;
+	tree -aC -I '.git|node_modules' --dirsfirst "$@" | less -FRNX
 }
 
 # `git-sync` is a wrapper function around `find`, `xargs` that will
@@ -162,10 +162,10 @@ function tre() {
 # down from the specified path.
 function git-sync {
 	if [[ -z "${1}" ]]; then
-		echo "ERROR: Please specify a path to sync";
-		return 1;
+		echo "ERROR: Please specify a path to sync"
+		return 1
 	fi
-	find "${1}" -maxdepth 2 -mindepth 2 -type d -name '.git' -print0 | xargs -P 8 -0 -I % bash -c 'git -C %/.. pull --rebase --autostash --quiet || echo "Failed updating: %"';
+	find "${1}" -maxdepth 2 -mindepth 2 -type d -name '.git' -print0 | xargs -P 8 -0 -I % bash -c 'git -C %/.. pull --rebase --autostash --quiet || echo "Failed updating: %"'
 }
 
 # `git-fetch` is a wrapper function around `find`, `xargs` that will
@@ -173,8 +173,8 @@ function git-sync {
 # down from the specified path.
 function git-fetch {
 	if [[ -z "${1}" ]]; then
-		echo "ERROR: Please specify a path to sync";
-		return 1;
+		echo "ERROR: Please specify a path to sync"
+		return 1
 	fi
-	find "${1}" -maxdepth 2 -mindepth 2 -type d -name '.git' -print0 | xargs -P 8 -0 -I % bash -c 'git -C %/.. fetch --all --prune --prune-tags --quiet || echo "Failed updating: %"';
+	find "${1}" -maxdepth 2 -mindepth 2 -type d -name '.git' -print0 | xargs -P 8 -0 -I % bash -c 'git -C %/.. fetch --all --prune --prune-tags --quiet || echo "Failed updating: %"'
 }
