fix accidental shell exit in git-sync and git-fetch functions

diff --git a/stow/shell/dot-functions b/stow/shell/dot-functions
--- a/stow/shell/dot-functions
+++ b/stow/shell/dot-functions
@@ -161,20 +161,20 @@ function tre() {
 # asynchrounously call git pull --rebase --autostash on any repository one level
 # down from the specified path.
 function git-sync {
-	if [[ -z $1 ]]; then
-		echo "Please specify a path to sync"
-		exit 1
+	if [[ -z "${1}" ]]; then
+		echo "ERROR: Please specify a path to sync";
+		return 1;
 	fi
-	find "${1}" -maxdepth 2 -mindepth 2 -type d -name '.git' -print0 | xargs -P 8 -0 -I % bash -c 'git -C %/.. pull --rebase --autostash --quiet || echo "Failed updating: %"'
+	find "${1}" -maxdepth 2 -mindepth 2 -type d -name '.git' -print0 | xargs -P 8 -0 -I % bash -c 'git -C %/.. pull --rebase --autostash --quiet || echo "Failed updating: %"';
 }
 
 # `git-fetch` is a wrapper function around `find`, `xargs` that will
 # asynchrounously call --all --prune --prune-tags --quiet on any repository one level
 # down from the specified path.
 function git-fetch {
-	if [[ -z $1 ]]; then
-		echo "Please specify a path to sync"
-		exit 1
+	if [[ -z "${1}" ]]; then
+		echo "ERROR: Please specify a path to sync";
+		return 1;
 	fi
-	find "${1}" -maxdepth 2 -mindepth 2 -type d -name '.git' -print0 | xargs -P 8 -0 -I % bash -c 'git -C %/.. fetch --all --prune --prune-tags --quiet || echo "Failed updating: %"'
+	find "${1}" -maxdepth 2 -mindepth 2 -type d -name '.git' -print0 | xargs -P 8 -0 -I % bash -c 'git -C %/.. fetch --all --prune --prune-tags --quiet || echo "Failed updating: %"';
 }
