feat: replace gitleaks with betterleaks within the dotfiles setup

diff --git a/stow/shell/.config/bash/functions b/stow/shell/.config/bash/functions
--- a/stow/shell/.config/bash/functions
+++ b/stow/shell/.config/bash/functions
@@ -215,9 +215,9 @@ function uuidgen() {
 	powershell -Command "[guid]::NewGuid().ToString()"
 }
 
-# `handle-secrets` is a wrapper function around `gitleaks` and allows you to
-# interactively go through any finding gitleaks detects in the supplied folder
-# and put them into a `.gitleaksignore` file with appropriate comments
+# `handle-secrets` is a wrapper function around `betterleaks` and allows you to
+# interactively go through any finding betterleaks detects in the supplied folder
+# and put them into a `.betterleaksignore` file with appropriate comments
 function handle-secrets() {
 	local target_directory report_directory report_file git_name git_email git_user ignore_file_contents current_time description rule file fingerprint commit secret comment documented_as
 
@@ -230,8 +230,8 @@ function handle-secrets() {
 	ignore_file_contents=""
 	current_time=$(date +"%Y-%m-%dT%H:%M")
 
-	if ! command -v gitleaks >/dev/null; then
-		echo "gitleaks not installed, cannot scan for secrets"
+	if ! command -v betterleaks >/dev/null; then
+		echo "betterleaks not installed, cannot scan for secrets"
 		return 1
 	fi
 
@@ -241,13 +241,13 @@ function handle-secrets() {
 	fi
 
 	echo "Scanning: ${target_directory}"
-	if [[ -f "${target_directory}/.gitleaksignore" ]]; then
-		ignore_file_contents=$(<"${target_directory}/.gitleaksignore")
+	if [[ -f "${target_directory}/.betterleaksignore" ]]; then
+		ignore_file_contents=$(<"${target_directory}/.betterleaksignore")
 		ignore_file_contents+="\n"
 	else
-		ignore_file_contents="# https://github.com/gitleaks/gitleaks\n\n"
+		ignore_file_contents="# https://github.com/betterleaks/betterleaks\n\n"
 	fi
-	gitleaks git --verbose --report-format=json --report-path="${report_file}" \
+	betterleaks git --verbose --report-format=json --report-path="${report_file}" \
 		--max-decode-depth 3 --max-archive-depth 3 \
 		--exit-code=0 "${target_directory}" &>/dev/null
 
@@ -289,10 +289,10 @@ function handle-secrets() {
 		done
 
 		if [[ -n "${ignore_file_contents}" ]]; then
-			echo -e "${ignore_file_contents}" >"${target_directory}/.gitleaksignore"
-			echo "All secrets handled and written to: '${target_directory}/.gitleaksignore'"
+			echo -e "${ignore_file_contents}" >"${target_directory}/.betterleaksignore"
+			echo "All secrets handled and written to: '${target_directory}/.betterleaksignore'"
 		fi
 	else
-		echo "gitleaks did not generate a report as expected, something may have gone wrong"
+		echo "betterleaks did not generate a report as expected, something may have gone wrong"
 	fi
 }
